from datetime import datetime

from sqlalchemy import Column
from sqlalchemy import DateTime
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import LargeBinary
from sqlalchemy import String

from database import Base


# =========================================================
# PASSKEY CREDENTIAL TABLE
# =========================================================

class PasskeyCredential(Base):

    __tablename__ = "passkey_credentials"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    user_id = Column(
        Integer,
        ForeignKey("users.id"),
        nullable=False,
        index=True
    )

    # WebAuthn credential ID
    credential_id = Column(
        LargeBinary,
        unique=True,
        nullable=False,
        index=True
    )

    # Public key generated by the authenticator
    credential_public_key = Column(
        LargeBinary,
        nullable=False
    )

    # Signature counter used to detect replay/cloned credentials
    sign_count = Column(
        Integer,
        default=0,
        nullable=False
    )

    # Optional authenticator transports
    transports = Column(
        String(255),
        nullable=True
    )

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False
    )


# =========================================================
# WEBAUTHN CHALLENGE TABLE
# =========================================================

class PasskeyChallenge(Base):

    __tablename__ = "passkey_challenges"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    user_id = Column(
        Integer,
        ForeignKey("users.id"),
        nullable=False,
        index=True
    )

    # Random challenge generated for one ceremony
    challenge = Column(
        LargeBinary,
        nullable=False
    )

    # REGISTRATION or AUTHENTICATION
    purpose = Column(
        String(30),
        nullable=False
    )

    # Challenge expiration time
    expires_at = Column(
        DateTime,
        nullable=False
    )

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False
    )